version: "3"

services:
  dev:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    env_file:
      - ../.env
  test:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    env_file:
      - ../.env
    environment:
      - CI=true
    command: yarn test
