const data = {
    en: {
        fields: {
            first_name: 'First name',
            last_name: 'Last name',
            address: 'Street Address',
            city: 'City',
            state: 'State',
            telephone: 'Telephone',
            specialty: 'Specialty',
            office_hours: 'Office Hours'
        },
        errors: {
            first_name: 'First name must be present',
            last_name: 'Last name is required',
            address: 'Street Address is required',
            city: 'City name is required',
            state: 'Please enter the state',
            telephone: 'Telephone number must be present',
            specialty: 'Specialty is required',
            office_hours: 'Office hours are needed',
        },
        title: 'Create A New Vet ...',
        address_heading: 'Home Address',
        add_button: 'Add vet',
        cancel_button: 'Cancel',
        edit_button: 'Update',
        delete_button: 'Delete',
        new_vet_button: 'New Vet',
        hours: 'Hours',
    },
    es: {
        fields: {
            first_name: 'Nombre',
            last_name: 'Apellido',
            address: 'Domicilio',
            city: 'Ciudad',
            state: 'Estado',
            telephone: 'El número de teléfono',
            specialty: 'Especialidad',
            office_hours: 'Horas de oficina'
        },
        errors: {
            first_name: 'El nombre debe tener un valor',
            last_name: 'El apellido es obligatorio',
            address: 'Domicilio es obligatorio',
            city: 'Se requiere el nombre de la ciudad',
            state: 'Por favor ingrese el estado',
            telephone: 'El número de teléfono debe estar presente.',
            specialty: 'El especialidad est obligatorio',
            office_hours: 'Se requieren horas de oficina',
        },
        title: 'Crear un nuevo veterinario ...',
        address_heading: 'Dirección completa',
        add_button: 'Añadir',
        cancel_button: 'Cancelar',
        edit_button: 'Editar',
        delete_button: 'Eliminar',
        new_vet_button: 'Nuevo veterinario',
        hours: 'Horas',
    },
    fr: {
        fields: {
            first_name: 'Prénom',
            last_name: 'Nom de famille',
            address: 'Adresse de rue',
            city: 'Ville',
            state: 'Etat',
            telephone: 'Téléphone',
            specialty: 'Spécialité',
            office_hours: 'Les heures de bureau',
        },
        errors: {
            first_name: 'Le prénom est requis',
            last_name: 'Le nom de famille est obligatorie',
            address: 'L\'adresse de la rue est nécessaire',
            city: 'La ville est obligatorie',
            state: 'L\'État doit être présent',
            telephone: 'Le numéro de téléphone est requis',
            specialty: 'Une spécialité est requise',
            office_hours: 'Les heures de bureau sont nécessaires',
        },
        title: 'Créer un nouveau vétérinaire ...',
        address_heading: 'Adresse du domicile',
        add_button: 'Ajouter',
        cancel_button: 'Annuler',
        edit_button: 'Réviser',
        delete_button: 'Effacer',
        new_vet_button: 'Nouvelle vétérinaire',
        hours: 'Heures',
    }
}

export { data }